# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
pool:
  # name: 'Azure Pipelines'
  # name: 'Default'
  name: 'agentPoolScaleSet2'

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
      - task: CmdLine@2
        displayName: 'Test dependency packages'
        inputs:
          script: |
            sudo apt install docker.io -y
            sudo usermod -aG docker $USER
            sudo chmod 777 /var/run/docker.sock
            docker images
            docker --version
            docker system prune -af
            docker image prune -af

#     - task: Docker@2
#       displayName: Build an image
#       inputs:
#         command: build
#         dockerfile: '$(Build.SourcesDirectory)/apache-php/Dockerfile'
#         tags: |
#           $(tag)
      - task: CmdLine@2
        inputs:
          script: |
            echo Write your commands here
            
            echo Hello world
